### PR TITLE
fix: remove deprecated parent pom

### LINKED ISSUE #1784: org.sonatype.oss:oss-parent is deprecated and should be removed
```
 <parent>
    <groupId>org.sonatype.oss</groupId>
    <artifactId>oss-parent</artifactId>
    <version>7</version>
  </parent>
  ```

### PR DESCRIPTION
**Pull request by elharo**
@Neenu1995 @suztomo fixes #1784

### CODE REVIEW

**Comment by suztomo** [comment]
I ran the diff in the effective poms on `google-api-java-client/google-api-client/pom.xml` below.

Would you add a description field in the parent pom?

```
suztomo-macbookpro44% git diff /tmp/google-api-client.master.pom /tmp/google-api-client.i1784.pom
diff --git a/tmp/google-api-client.master.pom b/tmp/google-api-client.i1784.pom
index 4f93633e..34b1d9a5 100644
--- a/tmp/google-api-client.master.pom
+++ b/tmp/google-api-client.i1784.pom
@@ -23,7 +23,7 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
 <?xml version="1.0" encoding="UTF-8"?>
 <!-- ====================================================================== -->
 <!--                                                                        -->
-<!-- Generated by Maven Help Plugin on 2021-05-04T13:04:31-04:00            -->
+<!-- Generated by Maven Help Plugin on 2021-05-04T13:05:00-04:00            -->
 <!-- See: http://maven.apache.org/plugins/maven-help-plugin/                -->
 <!--                                                                        -->
 <!-- ====================================================================== -->
@@ -44,7 +44,6 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
   <artifactId>google-api-client</artifactId>
   <version>1.31.5-SNAPSHOT</version>
   <name>Google APIs Client Library for Java</name>
-  <description>Sonatype helps open source projects to set up Maven repositories on https://oss.sonatype.org/</description>
   <url>https://github.com/googleapis/google-api-java-client/google-api-client</url>
   <inceptionYear>2010</inceptionYear>
   <organization>
@@ -67,18 +66,6 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
     <system>GitHub</system>
     <url>https://github.com/googleapis/google-api-java-client/issues</url>
   </issueManagement>
-  <distributionManagement>
-    <repository>
-      <id>sonatype-nexus-staging</id>
-      <name>Nexus Release Repository</name>
-      <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
-    </repository>
-    <snapshotRepository>
-      <id>sonatype-nexus-snapshots</id>
-      <name>Sonatype Nexus Snapshots</name>
-      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
-    </snapshotRepository>
-  </distributionManagement>
   <properties>
     <deploy.autorelease>false</deploy.autorelease>
     <os.detected.arch>x86_64</os.detected.arch>
@@ -100,7 +87,6 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
     <project.protobuf-java.version>3.15.8</project.protobuf-java.version>
     <project.servlet-api.version>2.5</project.servlet-api.version>
     <project.xpp3.version>1.1.4c</project.xpp3.version>
-    <sonatypeOssDistMgmtSnapshotsUrl>https://oss.sonatype.org/content/repositories/snapshots/</sonatypeOssDistMgmtSnapshotsUrl>
   </properties>
   <dependencyManagement>
     <dependencies>
@@ -350,17 +336,6 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
     </dependency>
   </dependencies>
   <repositories>
-    <repository>
-      <releases>
-        <enabled>false</enabled>
-      </releases>
-      <snapshots>
-        <enabled>true</enabled>
-      </snapshots>
-      <id>sonatype-nexus-snapshots</id>
-      <name>Sonatype Nexus Snapshots</name>
-      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
-    </repository>
     <repository>
       <snapshots>
         <enabled>false</enabled>
@@ -521,12 +496,7 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
         </plugin>
         <plugin>
           <artifactId>maven-release-plugin</artifactId>
-          <version>2.1</version>
-          <configuration>
-            <mavenExecutorId>forked-path</mavenExecutorId>
-            <useReleaseProfile>false</useReleaseProfile>
-            <arguments>-Psonatype-oss-release</arguments>
-          </configuration>
+          <version>2.5.3</version>
         </plugin>
       </plugins>
     </pluginManagement>
@@ -544,7 +514,6 @@ Effective POMs, after inheritance, interpolation, and profiles are applied:
               <rules>
                 <requireMavenVersion>
                   <version>[3.5.4,4.0.0)</version>
-                  <message>Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively.</message>
                 </requireMavenVersion>
               </rules>
             </configuration>
```

For the repository configuration, I believe Yoshi team's file uploading does not read the `distributionManagement` element.

**Comment by elharo** [comment]
What do you want the description field to say? The old description was simply incorrect so removing it completely is a step forward, and adding a new one is a separate issue.

**Comment by suztomo** [comment]
> What do you want the description field to say?

Let's put "The Google APIs Client Library for Java is a flexible, efficient, and powerful Java client library for accessing any HTTP-based API on the web, not just Google APIs." (from the README.md of this repository)

**Comment by suztomo** [comment]
My concern on the description tag is that the nexus staging repository might require the field. If it doesn't require, then that's fine.

**Review by suztomo — APPROVED** [review]

**Review by Neenu1995 — APPROVED** [review]

**Comment by elharo** [comment]
Good point. Added.

**Pull request merged**
