### PR TITLE
Possible implementation of resumable uploads.

### PR DESCRIPTION
**Pull request by geoffgibbs**
I have used this variation of the MediaHttpUploader to allow for resumable uploads to be paused and restarted in a project of my own.

### CODE REVIEW

**Comment by IvanRF** [comment]
Could you include an example on how you use it?

I guess that you set a listener `request.getMediaHttpUploader().setProgressListener(MediaHttpUploaderProgressListener);` and on every `UploadState.MEDIA_IN_PROGRESS` you store the current state with the new `getResumableUploadUrl()`.
Now, to continue with a previous upload I guess you use `continueResumableUpload(String resumableUploadUrl)` on a new request.

I think, instead of having two different functions calling `doResumableUpload(String)`, wouldn't be better to have a `setResumableUploadUrl(String)` which modifies current variables in order  to always use the current `resumableUpload(GenericUrl)`. This way, after you create a request you can set the resumable URL if exists, and continue with the execution.

In my case, I use exponential backoff for all executions on `AbstractGoogleClientRequest`. Having to call `continueResumableUpload(String)` will break that abstraction, that's why I think a `setResumableUploadUrl(String)` would be better.

**Comment by geoffgibbs** [comment]
That is how I'm using it in my code. But, to be honest, that was used to fix a specific problem at a specific time and I haven't had the need to go back to it before now.

I'll take another look and see what I can do.

**Comment by geoffgibbs** [comment]
I signed it?!

**Comment by chingor13** [comment]
Resumable uploads is available.

**Comment by IvanRF** [comment]
@chingor13 this is a related issue: https://github.com/googleapis/google-api-java-client/issues/995
If that issue is solved now, could you post a link to the new code? thanks!

**Comment by kbboss** [comment]
@chingor13  yep,how do you did it? post it,if you sloved it

**Comment by dknchris** [comment]
@geoffgibbs Can you please share a gist of how to actually use the resumable upload?

**Pull request closed without merging**
