### PR TITLE
fix: use Gson instead of Jackson

### PR DESCRIPTION
**Pull request by elharo**
@BenWhitehead

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
Ping ping ping

**Review by chingor13 — APPROVED** [review]

**Comment by hiranya911** [comment]
@chingor13 @elharo 

Can you share some context on why this change was made? This change is making it difficult for us (Firebase) to upgrade our SDK dependency from Google API client 1.30.x to 1.31.x. The use of Gson significantly changes how certain JSON input is handled, which is causing numerous test failures in our code.

**Comment by elharo** [comment]
go/json-madness

**Comment by hiranya911** [comment]
Thanks @elharo. I've submitted a detailed bug report with our findings at #1779

**Pull request merged**
