### PR TITLE
adds methods to create delegated credentials and builder

### PR DESCRIPTION
**Pull request by hgschmie**
adds a toBuilder() method which creates a mutable version of the credential
object preloaded with all values from the credential.

adds a createDelegated(String user) method which allows creation of
a credential with correct user delegation from an existing credential

### CODE REVIEW

**Comment by hgschmie** [comment]
the ci build seems to be broken (and fails with some android error message).

**Comment by nbali** [comment]
is there any reason this hasn't been merged?

**Comment by woodyspawnshop** [comment]
This would require more elaborate changes from folks to take advantage of. What I did in #1036 was take an existing flow with an existing function with existing overloads and simply added one overload to allow supplying the impersonation user. In order for folks to take advantage of that they simply pass an additional parameter. IMO both of these are probably helpful if they don't conflict.

**Comment by nbali** [comment]
TBH I prefer this one, but it's ridiculous that this comes up literally at every project I work with and had to work around it... so it annoyed me to the level that I wanted create a contribution about it. You can imagine my surprise when there are multiple, but they are blatantly ignored for so long.

**Comment by nbali** [comment]
@jadekler ping

**Comment by jadekler** [comment]
This client library is supported but in maintenance mode only, unfortunately. We are mostly in a bug-fixing, security-patching mode. Furthermore, this library is currently frozen while we clean up some of the internals and prepare for a release (hopefully making future releases easier). I'll keep this PR open and we'll circle back to this when we're done.

**Comment by nbali** [comment]
@jadekler the bothering lack of any ETA means this could take a very long time?

**Comment by nbali** [comment]
"we'll circle back to this when we're done." @jadekler @chingor13 any estimation when might that happen?

**Comment by chingor13** [comment]
This feature is currently available in the newer google-auth-library-java (com.google.auth:google-auth-library-oauth2-http). It's weird that there are 2 implementations for service accounts (and application default credentials) and we'd like to consolidate into 1 if possible.

The `GoogleCredentials` provided from the google-auth-library-java will work the the google-http-java-client (the underlying transport), but there's not great documentation on how to do it. It's *likely* that we'll create a guide for using those credentials and deprecated the ones here, rather than adding more features to the implementation here. This is only in the proposal stage and we're thinking about what changes need to be made to get these libraries where we want them.

**Comment by chingor13** [comment]
Verified that these commits rebased pass CI.

**Pull request merged**
