### PR TITLE
ci: fix the google style error in lint task in GitHub Actions

### LINKED ISSUE #1697: GitHub Actions: Fix formatting check failure
Part of #1691.

### PR DESCRIPTION
**Pull request by suztomo**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-api-java-client/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1697  ☕️

### CODE REVIEW

**Comment by suztomo** [comment]
Now it passes the "lint" check.

**Review by elharo — APPROVED** [review]

**Review by elharo — COMMENTED** [review]
Error: ] Some problems were encountered while processing the POMs:
Warning:  'parent.relativePath' of POM com.google.cloud:google-api-client-snippets:1.0.21 (/home/runner/work/google-api-java-client/google-api-java-client/samples/snippets/pom.xml) points at com.google.cloud:google-cloud-google-api-client-samples instead of com.google.cloud.samples:shared-configuration, please verify your project structure @ line 14, column 11
Error:  'dependencies.dependency.version' for com.google.api-client:google-api-client:jar is missing. @ line 41, column 17
 @ 
Error:  The build could not read 1 project -> [Help 1]
Error:    
Error:    The project com.google.cloud:google-api-client-snippets:1.0.21 (/home/runner/work/google-api-java-client/google-api-java-client/samples/snippets/pom.xml) has 1 error
Error:      'dependencies.dependency.version' for com.google.api-client:google-api-client:jar is missing. @ line 41, column 17
Error:

**Comment by suztomo** [comment]
@elharo That ("samples / checkstyle (pull_request)")'s going to be a next PR. I started working on it.

**Review by advsalahuddinahmed072 — COMMENTED** [review]
[Google Books ](https://books.google.com.bd/books/about/The_All_Pakistan_Legal_Decisions.html?id=V08-AQAAIAAJ&source=kp_book_description&redir_esc=y)

**Comment by advsalahuddinahmed072** [comment]
[P.L.D. 1969](https://books.google.com.bd/books/about/The_All_Pakistan_Legal_Decisions.html?id=5y8-AQAAIAAJ&printsec=frontcover&source=kp_read_button&hl=en&redir_esc=y) 

>

**Comment by advsalahuddinahmed072** [comment]
Download

**Review by advsalahuddinahmed072 — COMMENTED** [review]
@advsalahuddinahmed072 #2190 [The All Pakistan Legal Decisions ](https://books.google.com.bd/books/about/The_All_Pakistan_Legal_Decisions.html?id=5y8-AQAAIAAJ&printsec=frontcover&source=kp_read_button&hl=en&redir_esc=y)

**Pull request merged**
