### PR TITLE
fix: re-encode public keys from google.jks into p12 format for android

### LINKED ISSUE #1570: GoogleNetHttpTransport errors on Android - results in JKS not found exception
#### Environment details

1. General
2. OS type and version: Windows 10, v2004
3. Java version: 8
4. google-api-client version(s): 1.30.9

#### Steps to reproduce

1. Add `com.google.api-client:google-api-client-android:1.30.9` as dependency to an Android Studio project using Gradle
2. Add the following code to the `android` field in the app-level `build.gradle` file (this is a fix for a separate issue - without this fix, the app won't execute. See the linked StackOverflow post in my references for more) :
```
packagingOptions{
        exclude 'META-INF/DEPENDENCIES'
}
```
3. Import `com.google.api.client.googleapis.javanet.GoogleNetHttpTransport` and `com.google.api.client.http.javanet.NetHttpTransport` in the project's main activity (or whatever activity will be run to show the error)
4. Put the following code in the Activity, such that it will run in some way. Due to the errors it throws, you'll either need to wrap it in a method that throws those errors or surround it in a try/catch. For this example, I wrapped it in a try/catch and put it in my main activity's `onCreate` method:
`final NetHttpTransport HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();`
5. When this line is encountered, an exception occurs (see stack trace below)

#### Code example (from my example application's main activity)

```java
package com.example.errorreproduction;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.http.javanet.NetHttpTransport;

import java.io.IOException;
import java.security.GeneralSecurityException;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {
            // Error occurs here
            final NetHttpTransport HTTP_TRANSPORT = GoogleNetHttpTransport.newTrustedTransport();
        } catch (GeneralSecurityException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

#### Stack trace
```
W/System.err: java.security.KeyStoreException: JKS not found
        at java.security.KeyStore.getInstance(KeyStore.java:890)
        at com.google.api.client.util.SecurityUtils.getJavaKeyStore(SecurityUtils.java:52)
        at com.google.api.client.googleapis.GoogleUtils.getCertificateTrustStore(GoogleUtils.java:84)
        at com.google.api.client.googleapis.javanet.GoogleNetHttpTransport.newTrustedTransport(GoogleNetHttpTransport.java:55)
        at com.example.errorreproduction.MainActivity.onCreate(MainActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    Caused by: java.security.NoSuchAlgorithmException: JKS KeyStore not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.Security.getImpl(Security.java:628)
        at java.security.KeyStore.getInstance(KeyStore.java:887)
    	... 19 more
```

#### External references such as API reference guides
- **`GoogleNetHttpTransport` documentation page**: https://googleapis.dev/java/google-api-client/latest/com/google/api/client/googleapis/javanet/GoogleNetHttpTransport.html
- **Java Google Drive API Quickstart:** https://developers.google.com/drive/api/v3/quickstart/java
- **Fix for `META-INF/DEPENDENCIES` execution error with Google API Java Client:** https://stackoverflow.com/questions/44342455/more-than-one-file-was-found-with-os-independent-path-meta-inf-license
- **Out of date StackOverflow "solutions" that suggest just not using `GoogleNetHttpTransport`:** https://stackoverflow.com/questions/39248453/googlenethttptransport-newtrustedtransport-returning-null/39249969#39249969 and https://stackoverflow.com/questions/18862779/storageserviceaccountsample-application-reports-keystore-jks-implementation-not
- **Deprecated API page for AndroidHttp transport, which one of the above StackOverflow solutions recommended**: https://googleapis.dev/java/google-http-client/latest/com/google/api/client/extensions/android/http/AndroidHttp.html
- **Google Sign-In for Android tutorial, which requires an HttpTransport to be used**: https://developers.google.com/identity/sign-in/android/backend-auth

#### Additional Information
I will admit that I'm not terribly familiar with what the difference between using a `GoogleNetHttpTransport` versus just using a `NetHttpTransport` for the linked API tutorials. However, based on the documentation for `GoogleNetHttpTransport`, it seems like it's the best choice to use whenever transports need to be used when dealing with Google API's, due to the extra layer of security it adds via the call to `GoogleUtils.getCertificateTrustStore()` in the method `newTrustedTransport()`. 

However, as can be seen in my stack trace, the call to `GoogleUtils.getCertificateTrustStore()` often (if not always) errors on Android, due to the program's inability to locate the necessary `JKS`. While I was able to find workarounds for this problem on StackOverflow and the like (see links above), all of them simply advocated for using `new NetHttpTransport()` in place of `GoogleNetHttpTransport.newTrustedTransport()`. (NOTE: some of them advocate for the use of `AndroidHttp` instead, but on the documentation page for `AndroidHttp`, it says that it is deprecated, and advocates for the use of `new NetHttpTransport()` instead). However, I'm hesitant to accept that solution blindly, as I'm assuming that `GoogleNetHttpTransport` is made more secure for a reason.

Is `GoogleNetHttpTransport` not intended for use on Android? If so, I never found that fact documented anywhere. If that is the case, what is the best alternative? I'm assuming that if simply using `new HttpTransport()` was sufficient security-wise, than `GoogleNetHttpTransport.newTrustedTransport()` wouldn't have a need to exist in the first place. I don't want to sacrifice my application's security for a hacky fix that I could only find in years-old StackOverflow posts, so I was hoping that someone could help clear this up for me.

NOTE: I've tried adding a keystore to the Android Studio project, but that doesn't appear to actually relay the keystore information to `GoogleNetHttpTransport`. If I'm missing something on that front, I would appreciate any info as to how to set up my keystore properly such that `GoogleNetHttpTransport` can access it. 

Thank you!

### PR DESCRIPTION
**Pull request by chingor13**
This might fix #1570 - repackage our public keys in google.jks into google.p12.

Repackage command:
```bash
keytool -importkeystore -srckeystore google.jks -destkeystore google.p12 -srcstoretype JKS -deststoretype PKCS12 -deststorepass notasecret
```

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
did something change in google.p12? Githb shows this as empty?

**Comment by chingor13** [comment]
> did something change in google.p12? Githb shows this as empty?

Perhaps the UI is confused as it's a binary file? When I run `ls -l google-api-client/src/main/resources/com/google/api/client/googleapis` from a fresh clone, I see the file size as `76476` bytes.

**Review by elharo — COMMENTED** [review]
Kokoro fails on java 7, look related

**Comment by chingor13** [comment]
> Kokoro fails on java 7, look related

Yeah, it's strange because it passes on GitHub actions with Java 7

**Comment by suztomo** [comment]
I just submitted cl/360677807, which would prevent the "Kokoro - Test: Java 7".

```
junit.framework.AssertionFailedError: expected:<70> but was:<0>
	at com.google.api.client.googleapis.GoogleUtilsTest.testGetCertificateTrustStore(GoogleUtilsTest.java:38)
```

Feel free to revert cl/360677807 if you still need the Kokoro check.

**Review by elharo — APPROVED** [review]

**Pull request merged**
